### ISSUE TITLE
Move each interface into related module.

### ISSUE THREAD

**Issue by ArminF1996** [itsmehdiabdi/awesome-provider-manager#1]
بهتره فایل هر interface تو ماژول مربوط به خودش باشه، به جای اینکه یه فولدر داشته باشیم و همه interface ها توش باشه.

**Comment by itsmehdiabdi** [comment]
> بهتره فایل هر interface تو ماژول مربوط به خودش باشه، به جای اینکه یه فولدر داشته باشیم و همه interface ها توش باشه.

مقاومتی روش ندارم و این که تو و اشکان جفتتون نظرتون اینه نظرمو میاره روی این حالت :))
فقط این موضوع راجع به types هم صدق می‌کنه.
مرسی که گفتی :100:

**Comment by itsmehdiabdi** [comment]
کامیت بالا این ایشو رو می‌بنده.
